Python/s2/ps_2_copy/Python 2/pd_ds/urls.py
from django.urls import path
from books.views import BookDetailView, BookView, AddBook, EventShow, BookDelete, BookDelete_OWN
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/", BookView.as_view(), name="book-list"),
    path("books/add_book/", AddBook.as_view(), name="book-add"),
    path("books/events/", EventShow.as_view(), name="events"),
    path("books/delete_book/<int:pk>/", BookDelete.as_view(), name="delete-book"),
    path("books/delete_book_own/<int:pk>/", BookDelete_OWN.as_view(), name="delete-book-own")
]

Python/s2/ps_2_copy/Python 2/books/models.py
from django.db import models
from django.urls import reverse

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey('books.Author', on_delete=models.CASCADE, null=True, blank=False)
    num_pages = models.IntegerField()
    published_date = models.DateField()
    hard_cover = models.BooleanField(default=False)

    def __str__(self):
        return self.title + " " + str(self.published_date)

    def get_absolute_url(self):
        return reverse('book-detail', args=[self.id])

class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=20)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    authors = models.ManyToManyField('books.Author')
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

# Create your models here.

Python/s2/ps_2_copy/Python 2/books/views.py
from django.shortcuts import render
from django.utils import timezone
from books.models import Book, Author, Event
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse_lazy

# Create your views here.


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book_detail.html'


class BookView(ListView):
    model = Book
    template_name = 'books/book_view.html'


class AddBook(CreateView):
    model = Book
    template_name = 'books/add_book.html'
    fields = ["title", 'author','num_pages','published_date','hard_cover']

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['authors'] = Author.objects.all()
        return data


class EventShow(TemplateView):
    model = Book
    template_name = 'books/event_view.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['events'] = Event.objects.filter(start_date__lte=timezone.now(), end_date__gte=timezone.now())
        return data


class BookDelete(DeleteView):
    model = Book
    template_name = 'books/delete_book.html'
    success_url = reverse_lazy("book-list")


class BookDelete_OWN(View):
    model = Book

    def get(self, request, pk):
        instance = Book.objects.filter(id = pk).first()
        if instance:
            instance.delete()
            return HttpResponseRedirect(reverse_lazy("book-list"))
        return HttpResponse("Object do not exists")

Python/s2/ps_2_copy/Python 2/books/templates/books/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 {{form.errors}}
 <form action=".", method="POST">{% csrf_token %}
        <label for="title"></label>
        <input type="text" name="title" id="title">
     <br><br>
        <label for="author"></label>
      <select name="author" id="author">
     {% for object in authors %}
        <option value="{{ object.id }}">{{ object.name }}</option>
     {% endfor %}
      </select>
     <br><br>
        <label for="num_pages"></label>
        <input type="number" name="num_pages" id="num_pages">
     <br><br>
        <label for="published_date"></label>
        <input type="date" name="published_date" id="published_date">
     <br><br>
     <input type="checkbox" id="hard_cover" name="hard_cover">
     <label for="hard_cover">hard cover</label>
     <br><br>
        <button type="submit" id="submit">Zatwierdź</button>
    </form>
</body>
</html>

Python/s2/ps_2_copy/Python 2/books/templates/books/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {{ object.title }}
</head>
<body>
<br>
<a href="{% url 'book-list' %}">Book list</a>
</body>
</html>

<!--# jak wyglada django template langague-->

<!--< div style = "color: {% if event.active %} grey {% else %} black {% endif %}">-->
<!--</div> w detail view dodac atrybut active -->

Python/s2/ps_2_copy/Python 2/books/templates/books/book_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for object in object_list %}
    <!-- Display Objects -->
    <li><a href="{% url 'book-detail' object.id %}">{{ object.title}}</a></li>
    <li>{{ object.author }}{{ object.author.pk }}</li>
    <li>{{ object.num_pages }}</li>
    <li>{{ object.published_date }}</li>
    <li>{{ object.hard_cover}}</li>
    <li><a href="{% url 'delete-book' object.id %}">Delete</a></li>
    <li><a href="{% url 'delete-book-own' object.id %}">Delete OWN</a></li>
    <hr/>
    <!-- If object_list is empty  -->
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}

    <a href="">Add new book</a>
</ul>
</body>
</html>

Python/s2/ps_2_copy/Python 2/books/templates/books/delete_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

Python/s2/ps_2_copy/Python 2/books/templates/books/event_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for event in events %}
    <li> {{ event.name }}</li>
    <ul>
        {% for author in event.authors.all %}
        <li>{{ author }}</li>
            <ul>
            {% for book in author.book_set.all %}
                 <li>{{ book.title }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>
</body>
</html>